export const BULLET_HEAVEN_CONSTANTS = {
  CANVAS_WIDTH: 600,
  CANVAS_HEIGHT: 800,
  PLAYER_SIZE: 30,
  BULLET_SIZE: 8,
  POWERUP_SIZE: 24,
  INITIAL_SPEED: 5,
  PLAYER_BULLET_SPEED: 10,
  ENEMY_BULLET_SPEED: 3,
};

export const BULLET_HEAVEN_ENGINE_CONSTANTS = BULLET_HEAVEN_CONSTANTS;
export const BULLET_HEAVEN_CONSTANTS_2 = BULLET_HEAVEN_CONSTANTS;
export const BULLET_HEAVEN_CONSTANTS_3 = BULLET_HEAVEN_CONSTANTS;
export const BULLET_HEAVEN_CONSTANTS_4 = BULLET_HEAVEN_CONSTANTS;
