export const NEON_COLORS = {
  primary: '#00ffff',
  secondary: '#ff00ff',
  accent: '#ffff00',
  success: '#00ff00',
  warning: '#ff8800',
  danger: '#ff0044',
  background: '#0a0a1a',
  surface: '#1a1a2e',
  text: '#ffffff',
  textDim: '#888888',
  perfect: '#00ffff',
  great: '#00ff00',
  good: '#ffff00',
  miss: '#ff0044',
  neonPink: '#ff6b9d',
  neonCyan: '#00d2ff',
  neonPurple: '#a855f7',
  neonBlue: '#3b82f6',
  neonGreen: '#22c55e',
  gold: '#ffd700',
  white: '#ffffff',
  darkPurple: 'rgba(26, 26, 46, 0.8)',
};

export const GAME_CONFIG = {
  perfectScore: 100,
  greatScore: 75,
  goodScore: 50,
  missScore: 0,
  perfectWindow: 50,
  greatWindow: 100,
  goodWindow: 150,
};

// Game IDs
export const GAME_IDS = {
  GAME_2048: '2048',
  TETRIS: 'tetris',
  SNAKE: 'snake',
  BOUNCE: 'bounce',
  FUSION_2048: 'fusion2048',
  MINESWEEPER: 'minesweeper',
  BEJEWEL: 'bejeweled',
  SUDOKU: 'sudoku',
  SUBWAY: 'subway',
  FIRE_ICE: 'fireice',
  GOLD_MINER: 'goldminer',
  PVZ: 'pvz',
  SKETCHOUT: 'sketchout',
  FLAPPY_BIRD: 'flappybird',
  PACMAN: 'pacman',
  STICKMAN_HOOK: 'stickmanhook',
  HEXGL: 'hexgl',
  TEMPLE_RUN: 'templerun',
  ONEVONE: 'onevone',
  CROSSCODE: 'crosscode',
  ZUMA: 'zuma',
  LINKLINK: 'linklink',
  SOKOBAN: 'sokoban',
  FINDDIFF: 'finddiff',
  ONESTROKE: 'onestroke',
  PINBALL: 'pinball',
  BOWLING: 'bowling',
  BILLIARDS: 'billiards',
  RINGTOSS: 'ringtoss',
  ENHANCED_BREAKOUT: 'enhancedbreakout',
  SKIING: 'skiing',
  DANCING_LINE: 'dancingline',
  SUBWAY2: 'subway2',
  CLIFF_RUNNER: 'cliffrunner',
  SPEED_ESCAPE: 'speedescape',
  COOP_RUN: 'cooprun',
  TETRIS_BATTLE: 'tetrisbattle',
  SNAKE_DUO: 'snakeduo',
  BUNNY_HUNTER: 'bunnyhunter',
  PINBALL_DUO: 'pinballduo',
  THUNDER: 'thunder',
  SPACE_SHOOTER: 'spaceshooter',
  TANK_BATTLE: 'tankbattle',
  BUBBLE_SHOOTER: 'bubbleshooter',
  ZOMBIE_SHOOTER: 'zombieshooter',
  MONOPOLY: 'monopoly',
  HAPPY_FARM: 'happyfarm',
  COOKING_MASTER: 'cookingmaster',
  SHOP_MASTER: 'shopmaster',
  FRUIT_NINJA: 'fruitninja',
  WHACK_A_MOLE: 'whackamole',
  COLOR_MATCH: 'colormatch',
  BRAIN_TEST: 'braintest',
  CHESS: 'chess',
  GOBANG: 'gobang',
  LUDO: 'ludo',
  TOWER_DEFENSE: 'towerdefense',
  CATAPULT_DEFENSE: 'catapultdefense',
  MAGIC_TOWER: 'magictower',
  DESERT_WAR: 'desertwar',
  ICE_AGE_DEFENSE: 'iceagedefense',
  RHYTHM_MASTER: 'rhythmmaster',
  DJ_MIXER: 'djmixer',
  PIANO_TILES: 'pianotiles',
  BEAT_RACER: 'beatracer',
  MUSIC_HERO: 'musichero',
  CANDY_CRUSH: 'candycrush',
  GEM_BLAST: 'gemblast',
  BUBBLE_POP: 'bubblepop',
  COOKIE_MATCH: 'cookiismatch',
  ANIMAL_MATCH: 'animalmatch',
  PIXEL_FIGHTER: 'pixelfighter',
  BRAWL_STARS: 'brawlstars',
  KARATE_CHAMP: 'karatechamp',
  SAMURAI_SLASH: 'samuraislash',
  WRESTLE_MANIA: 'wrestlemania',
  HUARONG_DAO: 'huarongdao',
  NUMBER_SLIDE: 'numberslide',
  PIPE_CONNECT: 'pipeconnect',
  MEMORY_MATCH: 'memorymatch',
  WORD_SEARCH: 'wordsearch',
  VIRTUAL_PET: 'virtualpet',
  FISH_TANK: 'fishtank',
  GARDEN_GARDEN: 'gardengarden',
  COOKIE_BAKERY: 'cookiebakery',
  POKEMON: 'pokemon',
  ANGRY_BIRDS: 'angrybirds',
  DOODLE_JUMP: 'doodlejump',
  BOWLING_MASTER: 'bowlingmaster',
  PINBALL_PHYSICS: 'pinballphysics',
  CUT_ROPE: 'cutrope',
};

// Storage keys
export const STORAGE_KEYS = {
  GAME_2048: 'game_2048_highscore',
  TETRIS: 'tetris_highscore',
  SNAKE: 'snake_highscore',
  BOUNCE: 'bounce_highscore',
  FUSION_2048: 'fusion2048_highscore',
  MINESWEEPER: 'minesweeper_highscore',
  BEJEWEL: 'bejeweled_highscore',
  SUDOKU: 'sudoku_highscore',
  SUBWAY: 'subway_highscore',
  FIRE_ICE: 'fireice_highscore',
  GOLD_MINER: 'goldminer_highscore',
  PVZ: 'pvz_highscore',
  SKETCHOUT: 'sketchout_highscore',
  FLAPPY_BIRD: 'flappybird_highscore',
  PACMAN: 'pacman_highscore',
  STICKMAN_HOOK: 'stickmanhook_highscore',
  HEXGL: 'hexgl_highscore',
  TEMPLE_RUN: 'templerun_highscore',
  ONEVONE: 'onevone_highscore',
  CROSSCODE: 'crosscode_highscore',
  ZUMA: 'zuma_highscore',
  LINKLINK: 'linklink_highscore',
  SOKOBAN: 'sokoban_highscore',
  FINDDIFF: 'finddiff_highscore',
  ONESTROKE: 'onestroke_highscore',
  PINBALL: 'pinball_highscore',
  BOWLING: 'bowling_highscore',
  BILLIARDS: 'billiards_highscore',
  RINGTOSS: 'ringtoss_highscore',
  ENHANCED_BREAKOUT: 'enhancedbreakout_highscore',
  SKIING: 'skiing_highscore',
  DANCING_LINE: 'dancingline_highscore',
  SUBWAY2: 'subway2_highscore',
  CLIFF_RUNNER: 'cliffrunner_highscore',
  SPEED_ESCAPE: 'speedescape_highscore',
  COOP_RUN: 'cooprun_highscore',
  TETRIS_BATTLE: 'tetrisbattle_highscore',
  SNAKE_DUO: 'snakeduo_highscore',
  BUNNY_HUNTER: 'bunnyhunter_highscore',
  PINBALL_DUO: 'pinballduo_highscore',
  THUNDER: 'thunder_highscore',
  SPACE_SHOOTER: 'spaceshooter_highscore',
  TANK_BATTLE: 'tankbattle_highscore',
  BUBBLE_SHOOTER: 'bubbleshooter_highscore',
  ZOMBIE_SHOOTER: 'zombieshooter_highscore',
  MONOPOLY: 'monopoly_highscore',
  HAPPY_FARM: 'happyfarm_highscore',
  COOKING_MASTER: 'cookingmaster_highscore',
  SHOP_MASTER: 'shopmaster_highscore',
  FRUIT_NINJA: 'fruitninja_highscore',
  WHACK_A_MOLE: 'whackamole_highscore',
  COLOR_MATCH: 'colormatch_highscore',
  BRAIN_TEST: 'braintest_highscore',
  CHESS: 'chess_highscore',
  GOBANG: 'gobang_highscore',
  LUDO: 'ludo_highscore',
  TOWER_DEFENSE: 'towerdefense_highscore',
  CATAPULT_DEFENSE: 'catapultdefense_highscore',
  MAGIC_TOWER: 'magictower_highscore',
  DESERT_WAR: 'desertwar_highscore',
  ICE_AGE_DEFENSE: 'iceagedefense_highscore',
  RHYTHM_MASTER: 'rhythmmaster_highscore',
  DJ_MIXER: 'djmixer_highscore',
  PIANO_TILES: 'pianotiles_highscore',
  BEAT_RACER: 'beatracer_highscore',
  MUSIC_HERO: 'musichero_highscore',
  CANDY_CRUSH: 'candycrush_highscore',
  GEM_BLAST: 'gemblast_highscore',
  BUBBLE_POP: 'bubblepop_highscore',
  COOKIE_MATCH: 'cookiismatch_highscore',
  ANIMAL_MATCH: 'animalmatch_highscore',
  PIXEL_FIGHTER: 'pixelfighter_highscore',
  BRAWL_STARS: 'brawlstars_highscore',
  KARATE_CHAMP: 'karatechamp_highscore',
  SAMURAI_SLASH: 'samuraislash_highscore',
  WRESTLE_MANIA: 'wrestlemania_highscore',
  HUARONG_DAO: 'huarongdao_highscore',
  NUMBER_SLIDE: 'numberslide_highscore',
  PIPE_CONNECT: 'pipeconnect_highscore',
  MEMORY_MATCH: 'memorymatch_highscore',
  WORD_SEARCH: 'wordsearch_highscore',
  VIRTUAL_PET: 'virtualpet_highscore',
  FISH_TANK: 'fishtank_highscore',
  GARDEN_GARDEN: 'gardengarden_highscore',
  COOKIE_BAKERY: 'cookiebakery_highscore',
  POKEMON: 'pokemon_highscore',
  ANGRY_BIRDS: 'angrybirds_highscore',
  DOODLE_JUMP: 'doodlejump_highscore',
  BOWLING_MASTER: 'bowlingmaster_highscore',
  PINBALL_PHYSICS: 'pinballphysics_highscore',
  CUT_ROPE: 'cutrope_highscore',
};

// All game constants
export const GAME_2048_CONSTANTS = { GRID_SIZE: 4, CELL_SIZE: 80, GAP: 10 };
export const FUSION_CONSTANTS = { GRID_SIZE: 6, CELL_SIZE: 70, GAP: 8, CANVAS_WIDTH: 500, CANVAS_HEIGHT: 500 };
export const TETRIS_CONSTANTS = { BOARD_WIDTH: 10, BOARD_HEIGHT: 20, CELL_SIZE: 30 };
export const SNAKE_CONSTANTS = { CELL_SIZE: 20, INITIAL_LENGTH: 3, SPEED: 150 };
export const MINESWEEPER_CONSTANTS = { ROWS: 16, COLS: 16, MINE_COUNT: 40 };
export const BEJEWEL_CONSTANTS = { GRID_SIZE: 8, CELL_SIZE: 50 };
export const SUDOKU_CONSTANTS = { GRID_SIZE: 9, CELL_SIZE: 50 };
export const FIRE_ICE_CONSTANTS = { CANVAS_WIDTH: 800, CANVAS_HEIGHT: 500 };
export const GOLD_MINER_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500 };
export const FLAPPY_BIRD_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 600, GRAVITY: 0.25, JUMP_FORCE: -6 };
export const PACMAN_CONSTANTS = { CANVAS_WIDTH: 560, CANVAS_HEIGHT: 620, CELL_SIZE: 28 };
export const STICKMAN_HOOK_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 700 };
export const HEXGL_CONSTANTS = { CANVAS_WIDTH: 800, CANVAS_HEIGHT: 600 };
export const TEMPLE_RUN_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 600 };
export const ONEVONE_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 400 };
export const CROSSCODE_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 600 };
export const ZUMA_CONSTANTS = { CANVAS_WIDTH: 800, CANVAS_HEIGHT: 600 };
export const SOKOBAN_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 500, CELL_SIZE: 50 };
export const RINGTOSS_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 600 };
export const SKIING_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 600 };
export const SPEED_ESCAPE_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 600 };
export const SPACE_SHOOTER_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 800 };
export const ZOMBIE_SHOOTER_CONSTANTS = { CANVAS_WIDTH: 800, CANVAS_HEIGHT: 600 };
export const FISH_TANK_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 400 };
export const PINBALL_DUO_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 700 };
export const BUNNY_HUNTER_CONSTANTS = { CANVAS_WIDTH: 800, CANVAS_HEIGHT: 500 };
export const TETRIS_BATTLE_CONSTANTS = { BOARD_WIDTH: 10, BOARD_HEIGHT: 20, CELL_SIZE: 25 };
export const SNAKE_DUO_CONSTANTS = { CELL_SIZE: 20, SPEED: 150 };
export const TANK_BATTLE_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 600 };
export const VIRTUAL_PET_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 600 };
export const POKEMON_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 600 };
export const BRAWL_STARS_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 500 };
export const PIXEL_FIGHTER_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 400 };
export const KARATE_CHAMP_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 500 };
export const SAMURAI_SLASH_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500 };
export const WRESTLE_MANIA_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 500 };
export const NUMBER_SLIDE_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 400, GRID_SIZE: 4, CELL_SIZE: 100 };
export const PIPE_CONNECT_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 500, GRID_SIZE: 5, CELL_SIZE: 100 };
export const MEMORY_MATCH_CONSTANTS = { CANVAS_WIDTH: 480, CANVAS_HEIGHT: 480, GRID_SIZE: 4 };
export const WORD_SEARCH_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 500, GRID_SIZE: 10 };
export const RHYTHM_MASTER_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 700, LANES: 5, NOTE_SIZE: 60, FALL_SPEED: 5 };
export const DJ_MIXER_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500, GRID_COLS: 8, GRID_ROWS: 4 };
export const PIANO_TILES_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 700, LANES: 4, TILE_HEIGHT: 120 };
export const BEAT_RACER_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500, CAR_WIDTH: 50, CAR_HEIGHT: 80 };
export const MUSIC_HERO_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 700, LANES: 4, NOTE_SIZE: 50 };
export const BOWLING_MASTER_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 600, LANE_LENGTH: 500 };
export const ANGRY_BIRDS_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500 };
export const DOODLE_JUMP_CONSTANTS = { CANVAS_WIDTH: 300, CANVAS_HEIGHT: 600, JUMP_VELOCITY: -15, GRAVITY: 0.5 };
export const PINBALL_PHYSICS_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 600, GRAVITY: 0.2 };
export const BUBBLE_POP_CONSTANTS = { CANVAS_WIDTH: 480, CANVAS_HEIGHT: 640, BUBBLE_RADIUS: 25 };
export const COOKIE_MATCH_CONSTANTS = { CANVAS_WIDTH: 480, CANVAS_HEIGHT: 480, GRID_SIZE: 8, CELL_SIZE: 60 };
export const ANIMAL_MATCH_CONSTANTS = { CANVAS_WIDTH: 480, CANVAS_HEIGHT: 480, GRID_SIZE: 8, CELL_SIZE: 60 };
export const COOKIE_BAKERY_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 500 };
export const GARDEN_GARDEN_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 500, GRID_SIZE: 5, CELL_SIZE: 100 };
export const BUBBLE_SHOOTER_CONSTANTS = { CANVAS_WIDTH: 480, CANVAS_HEIGHT: 640, BUBBLE_RADIUS: 20, ROWS: 12, COLS: 11 };
export const BILLIARDS_CONSTANTS = { CANVAS_WIDTH: 800, CANVAS_HEIGHT: 500, BALL_RADIUS: 12, FRICTION: 0.985 };
export const BOUNCE_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 600, PADDLE_WIDTH: 80, BALL_RADIUS: 10 };
export const BOWLING_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 700, BALL_RADIUS: 15, PIN_RADIUS: 8 };
export const PINBALL_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 700, FLIPPER_WIDTH: 80, BALL_RADIUS: 10 };
export const ENHANCED_BREAKOUT_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500, PADDLE_WIDTH: 100, BALL_RADIUS: 8 };
export const DANCING_LINE_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 700, LINE_WIDTH: 8 };
export const CLIFF_RUNNER_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 600, PLAYER_SIZE: 40, GRAVITY: 0.5, JUMP_FORCE: -12 };
export const COOP_RUN_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 400, PLAYER_SIZE: 30, SPEED: 3 };
export const HUARONG_DAO_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 500, CELL_SIZE: 100 };
export const THUNDER_CONSTANTS = { CANVAS_WIDTH: 480, CANVAS_HEIGHT: 700, PLAYER_WIDTH: 40, PLAYER_HEIGHT: 50, BULLET_WIDTH: 6, BULLET_HEIGHT: 15 };
export const MONOPOLY_CONSTANTS = { CANVAS_WIDTH: 700, CANVAS_HEIGHT: 700, SPACE_SIZE: 70, INITIAL_MONEY: 1500 };
export const HAPPY_FARM_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500, GRID_SIZE: 50 };
export const COOKING_MASTER_CONSTANTS = { CANVAS_WIDTH: 700, CANVAS_HEIGHT: 500 };
export const SHOP_MASTER_CONSTANTS = { CANVAS_WIDTH: 700, CANVAS_HEIGHT: 500 };
export const FRUIT_NINJA_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 700, SPAWN_INTERVAL: 800, GRAVITY: 0.3 };
export const WHACK_A_MOLE_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500, GRID_COLS: 3, GRID_ROWS: 3, HOLE_SIZE: 80, GAME_DURATION: 30 };
export const COLOR_MATCH_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 600, GRID_SIZE: 5, TILE_SIZE: 80, GAME_DURATION: 60 };
export const BRAIN_TEST_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 700, TOTAL_QUESTIONS: 10, TIME_LIMIT: 120 };
export const CHESS_CONSTANTS = { CANVAS_WIDTH: 560, CANVAS_HEIGHT: 620, CELL_SIZE: 70 };
export const GOBANG_CONSTANTS = { CANVAS_WIDTH: 560, CANVAS_HEIGHT: 560, GRID_SIZE: 15, CELL_SIZE: 35 };
export const LUDO_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 600, CELL_SIZE: 25 };
export const TOWER_DEFENSE_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500, GRID_SIZE: 40, INITIAL_MONEY: 200, INITIAL_LIVES: 20 };
export const CATAPULT_DEFENSE_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500, GRID_SIZE: 50, INITIAL_MONEY: 300 };
export const MAGIC_TOWER_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500, GRID_SIZE: 40, MANA_MAX: 100, INITIAL_MONEY: 200 };
export const DESERT_WAR_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500, GRID_SIZE: 50, INITIAL_MONEY: 250 };
export const ICE_AGE_DEFENSE_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500, GRID_SIZE: 40, INITIAL_MONEY: 200 };
export const CANDY_CRUSH_CONSTANTS = { CANVAS_WIDTH: 480, CANVAS_HEIGHT: 480, GRID_SIZE: 8, CELL_SIZE: 60 };
export const GEM_BLAST_CONSTANTS = { CANVAS_WIDTH: 480, CANVAS_HEIGHT: 480, GRID_SIZE: 8, CELL_SIZE: 60 };
export const CUT_ROPE_CONSTANTS = { CANVAS_WIDTH: 400, CANVAS_HEIGHT: 500 };
export const LINKLINK_CONSTANTS = { CANVAS_WIDTH: 600, CANVAS_HEIGHT: 500, GRID_SIZE: 8, CELL_SIZE: 60 };
export const FINDDIFF_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 500, TOTAL_LEVELS: 5, DIFFERENCES_PER_LEVEL: 5 };
export const ONESTROKE_CONSTANTS = { CANVAS_WIDTH: 500, CANVAS_HEIGHT: 500, NODE_RADIUS: 15 };
export const TILE_COLORS = { 2: '#eee4da', 4: '#ede0c8', 8: '#f2b179', 16: '#f59563', 32: '#f67c5f', 64: '#f65e3b', 128: '#edcf72', 256: '#edcc61', 512: '#edc850', 1024: '#edc53f', 2048: '#edc22e' };

// Engine constants (aliases)
export const TETRIS_ENGINE_CONSTANTS = TETRIS_CONSTANTS;
export const SNAKE_ENGINE_CONSTANTS = SNAKE_CONSTANTS;
export const MINESWEEPER_ENGINE_CONSTANTS = MINESWEEPER_CONSTANTS;
export const BEJEWEL_ENGINE_CONSTANTS = BEJEWEL_CONSTANTS;
export const SUDOKU_ENGINE_CONSTANTS = SUDOKU_CONSTANTS;
export const FIRE_ICE_ENGINE_CONSTANTS = FIRE_ICE_CONSTANTS;
export const GOLD_MINER_ENGINE_CONSTANTS = GOLD_MINER_CONSTANTS;
export const FLAPPY_BIRD_ENGINE_CONSTANTS = FLAPPY_BIRD_CONSTANTS;
export const PACMAN_ENGINE_CONSTANTS = PACMAN_CONSTANTS;
export const STICKMAN_HOOK_ENGINE_CONSTANTS = STICKMAN_HOOK_CONSTANTS;
export const HEXGL_ENGINE_CONSTANTS = HEXGL_CONSTANTS;
export const TEMPLE_RUN_ENGINE_CONSTANTS = TEMPLE_RUN_CONSTANTS;
export const ONEVONE_ENGINE_CONSTANTS = ONEVONE_CONSTANTS;
export const CROSSCODE_ENGINE_CONSTANTS = CROSSCODE_CONSTANTS;
export const ZUMA_ENGINE_CONSTANTS = ZUMA_CONSTANTS;
export const SOKOBAN_ENGINE_CONSTANTS = SOKOBAN_CONSTANTS;
export const RINGTOSS_ENGINE_CONSTANTS = RINGTOSS_CONSTANTS;
export const SKIING_ENGINE_CONSTANTS = SKIING_CONSTANTS;
export const SPEED_ESCAPE_ENGINE_CONSTANTS = SPEED_ESCAPE_CONSTANTS;
export const SPACE_SHOOTER_ENGINE_CONSTANTS = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_ENGINE_CONSTANTS = TANK_BATTLE_CONSTANTS;
export const ZOMBIE_SHOOTER_ENGINE_CONSTANTS = ZOMBIE_SHOOTER_CONSTANTS;
export const FISH_TANK_ENGINE_CONSTANTS = FISH_TANK_CONSTANTS;
export const PINBALL_DUO_ENGINE_CONSTANTS = PINBALL_DUO_CONSTANTS;
export const BUNNY_HUNTER_ENGINE_CONSTANTS = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_ENGINE_CONSTANTS = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_ENGINE_CONSTANTS = SNAKE_DUO_CONSTANTS;
export const BILLIARDS_ENGINE_CONSTANTS = BILLIARDS_CONSTANTS;
export const BOUNCE_ENGINE_CONSTANTS = BOUNCE_CONSTANTS;
export const BOWLING_ENGINE_CONSTANTS = BOWLING_CONSTANTS;
export const PINBALL_ENGINE_CONSTANTS = PINBALL_CONSTANTS;
export const ENHANCED_BREAKOUT_ENGINE_CONSTANTS = ENHANCED_BREAKOUT_CONSTANTS;
export const DANCING_LINE_ENGINE_CONSTANTS = DANCING_LINE_CONSTANTS;
export const CLIFF_RUNNER_ENGINE_CONSTANTS = CLIFF_RUNNER_CONSTANTS;
export const COOP_RUN_ENGINE_CONSTANTS = COOP_RUN_CONSTANTS;
export const HUARONG_DAO_ENGINE_CONSTANTS = HUARONG_DAO_CONSTANTS;
export const THUNDER_ENGINE_CONSTANTS = THUNDER_CONSTANTS;
export const MONOPOLY_ENGINE_CONSTANTS = MONOPOLY_CONSTANTS;
export const HAPPY_FARM_ENGINE_CONSTANTS = HAPPY_FARM_CONSTANTS;
export const COOKING_MASTER_ENGINE_CONSTANTS = COOKING_MASTER_CONSTANTS;
export const SHOP_MASTER_ENGINE_CONSTANTS = SHOP_MASTER_CONSTANTS;
export const FRUIT_NINJA_ENGINE_CONSTANTS = FRUIT_NINJA_CONSTANTS;
export const WHACK_A_MOLE_ENGINE_CONSTANTS = WHACK_A_MOLE_CONSTANTS;
export const COLOR_MATCH_ENGINE_CONSTANTS = COLOR_MATCH_CONSTANTS;
export const BRAIN_TEST_ENGINE_CONSTANTS = BRAIN_TEST_CONSTANTS;
export const CHESS_ENGINE_CONSTANTS = CHESS_CONSTANTS;
export const GOBANG_ENGINE_CONSTANTS = GOBANG_CONSTANTS;
export const LUDO_ENGINE_CONSTANTS = LUDO_CONSTANTS;
export const TOWER_DEFENSE_ENGINE_CONSTANTS = TOWER_DEFENSE_CONSTANTS;
export const CATAPULT_DEFENSE_ENGINE_CONSTANTS = CATAPULT_DEFENSE_CONSTANTS;
export const MAGIC_TOWER_ENGINE_CONSTANTS = MAGIC_TOWER_CONSTANTS;
export const DESERT_WAR_ENGINE_CONSTANTS = DESERT_WAR_CONSTANTS;
export const ICE_AGE_DEFENSE_ENGINE_CONSTANTS = ICE_AGE_DEFENSE_CONSTANTS;
export const RHYTHM_MASTER_ENGINE_CONSTANTS = RHYTHM_MASTER_CONSTANTS;
export const DJ_MIXER_ENGINE_CONSTANTS = DJ_MIXER_CONSTANTS;
export const PIANO_TILES_ENGINE_CONSTANTS = PIANO_TILES_CONSTANTS;
export const BEAT_RACER_ENGINE_CONSTANTS = BEAT_RACER_CONSTANTS;
export const MUSIC_HERO_ENGINE_CONSTANTS = MUSIC_HERO_CONSTANTS;
export const CANDY_CRUSH_ENGINE_CONSTANTS = CANDY_CRUSH_CONSTANTS;
export const GEM_BLAST_ENGINE_CONSTANTS = GEM_BLAST_CONSTANTS;
export const BUBBLE_POP_ENGINE_CONSTANTS = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_ENGINE_CONSTANTS = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_ENGINE_CONSTANTS = ANIMAL_MATCH_CONSTANTS;
export const BOWLING_MASTER_ENGINE_CONSTANTS = BOWLING_MASTER_CONSTANTS;
export const ANGRY_BIRDS_ENGINE_CONSTANTS = ANGRY_BIRDS_CONSTANTS;
export const DOODLE_JUMP_ENGINE_CONSTANTS = DOODLE_JUMP_CONSTANTS;
export const PINBALL_PHYSICS_ENGINE_CONSTANTS = PINBALL_PHYSICS_CONSTANTS;
export const CUT_ROPE_ENGINE_CONSTANTS = CUT_ROPE_CONSTANTS;
export const PIXEL_FIGHTER_ENGINE_CONSTANTS = PIXEL_FIGHTER_CONSTANTS;
export const BRAWL_STARS_ENGINE_CONSTANTS = BRAWL_STARS_CONSTANTS;
export const KARATE_CHAMP_ENGINE_CONSTANTS = KARATE_CHAMP_CONSTANTS;
export const SAMURAI_SLASH_ENGINE_CONSTANTS = SAMURAI_SLASH_CONSTANTS;
export const WRESTLE_MANIA_ENGINE_CONSTANTS = WRESTLE_MANIA_CONSTANTS;
export const NUMBER_SLIDE_ENGINE_CONSTANTS = NUMBER_SLIDE_CONSTANTS;
export const PIPE_CONNECT_ENGINE_CONSTANTS = PIPE_CONNECT_CONSTANTS;
export const MEMORY_MATCH_ENGINE_CONSTANTS = MEMORY_MATCH_CONSTANTS;
export const WORD_SEARCH_ENGINE_CONSTANTS = WORD_SEARCH_CONSTANTS;
export const VIRTUAL_PET_ENGINE_CONSTANTS = VIRTUAL_PET_CONSTANTS;
export const GARDEN_GARDEN_ENGINE_CONSTANTS = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_ENGINE_CONSTANTS = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_ENGINE_CONSTANTS = POKEMON_CONSTANTS;
export const BUBBLE_SHOOTER_ENGINE_CONSTANTS = BUBBLE_SHOOTER_CONSTANTS;

// Numbered variants
export const TETRIS_CONSTANTS_2 = TETRIS_CONSTANTS;
export const SNAKE_CONSTANTS_2 = SNAKE_CONSTANTS;
export const MINESWEEPER_CONSTANTS_2 = MINESWEEPER_CONSTANTS;
export const BEJEWEL_CONSTANTS_2 = BEJEWEL_CONSTANTS;
export const SUDOKU_CONSTANTS_2 = SUDOKU_CONSTANTS;
export const FIRE_ICE_CONSTANTS_2 = FIRE_ICE_CONSTANTS;
export const GOLD_MINER_CONSTANTS_2 = GOLD_MINER_CONSTANTS;
export const FLAPPY_BIRD_CONSTANTS_2 = FLAPPY_BIRD_CONSTANTS;
export const PACMAN_CONSTANTS_2 = PACMAN_CONSTANTS;
export const STICKMAN_HOOK_CONSTANTS_2 = STICKMAN_HOOK_CONSTANTS;
export const HEXGL_CONSTANTS_2 = HEXGL_CONSTANTS;
export const TEMPLE_RUN_CONSTANTS_2 = TEMPLE_RUN_CONSTANTS;
export const ONEVONE_CONSTANTS_2 = ONEVONE_CONSTANTS;
export const CROSSCODE_CONSTANTS_2 = CROSSCODE_CONSTANTS;
export const ZUMA_CONSTANTS_2 = ZUMA_CONSTANTS;
export const SOKOBAN_CONSTANTS_2 = SOKOBAN_CONSTANTS;
export const RINGTOSS_CONSTANTS_2 = RINGTOSS_CONSTANTS;
export const SKIING_CONSTANTS_2 = SKIING_CONSTANTS;
export const SPEED_ESCAPE_CONSTANTS_2 = SPEED_ESCAPE_CONSTANTS;
export const SPACE_SHOOTER_CONSTANTS_2 = SPACE_SHOOTER_CONSTANTS;
export const ZOMBIE_SHOOTER_CONSTANTS_2 = ZOMBIE_SHOOTER_CONSTANTS;
export const FISH_TANK_CONSTANTS_2 = FISH_TANK_CONSTANTS;
export const PINBALL_DUO_CONSTANTS_2 = PINBALL_DUO_CONSTANTS;
export const BUNNY_HUNTER_CONSTANTS_2 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_CONSTANTS_2 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_CONSTANTS_2 = SNAKE_DUO_CONSTANTS;
export const TANK_BATTLE_CONSTANTS_2 = TANK_BATTLE_CONSTANTS;
export const BILLIARDS_CONSTANTS_2 = BILLIARDS_CONSTANTS;
export const BOUNCE_CONSTANTS_2 = BOUNCE_CONSTANTS;
export const BOWLING_CONSTANTS_2 = BOWLING_CONSTANTS;
export const PINBALL_CONSTANTS_2 = PINBALL_CONSTANTS;
export const ENHANCED_BREAKOUT_CONSTANTS_2 = ENHANCED_BREAKOUT_CONSTANTS;
export const DANCING_LINE_CONSTANTS_2 = DANCING_LINE_CONSTANTS;
export const CLIFF_RUNNER_CONSTANTS_2 = CLIFF_RUNNER_CONSTANTS;
export const COOP_RUN_CONSTANTS_2 = COOP_RUN_CONSTANTS;
export const HUARONG_DAO_CONSTANTS_2 = HUARONG_DAO_CONSTANTS;
export const THUNDER_CONSTANTS_2 = THUNDER_CONSTANTS;
export const MONOPOLY_CONSTANTS_2 = MONOPOLY_CONSTANTS;
export const HAPPY_FARM_CONSTANTS_2 = HAPPY_FARM_CONSTANTS;
export const COOKING_MASTER_CONSTANTS_2 = COOKING_MASTER_CONSTANTS;
export const SHOP_MASTER_CONSTANTS_2 = SHOP_MASTER_CONSTANTS;
export const FRUIT_NINJA_CONSTANTS_2 = FRUIT_NINJA_CONSTANTS;
export const WHACK_A_MOLE_CONSTANTS_2 = WHACK_A_MOLE_CONSTANTS;
export const COLOR_MATCH_CONSTANTS_2 = COLOR_MATCH_CONSTANTS;
export const BRAIN_TEST_CONSTANTS_2 = BRAIN_TEST_CONSTANTS;
export const CHESS_CONSTANTS_2 = CHESS_CONSTANTS;
export const GOBANG_CONSTANTS_2 = GOBANG_CONSTANTS;
export const LUDO_CONSTANTS_2 = LUDO_CONSTANTS;
export const TOWER_DEFENSE_CONSTANTS_2 = TOWER_DEFENSE_CONSTANTS;
export const CATAPULT_DEFENSE_CONSTANTS_2 = CATAPULT_DEFENSE_CONSTANTS;
export const MAGIC_TOWER_CONSTANTS_2 = MAGIC_TOWER_CONSTANTS;
export const DESERT_WAR_CONSTANTS_2 = DESERT_WAR_CONSTANTS;
export const ICE_AGE_DEFENSE_CONSTANTS_2 = ICE_AGE_DEFENSE_CONSTANTS;
export const RHYTHM_MASTER_CONSTANTS_2 = RHYTHM_MASTER_CONSTANTS;
export const DJ_MIXER_CONSTANTS_2 = DJ_MIXER_CONSTANTS;
export const PIANO_TILES_CONSTANTS_2 = PIANO_TILES_CONSTANTS;
export const BEAT_RACER_CONSTANTS_2 = BEAT_RACER_CONSTANTS;
export const MUSIC_HERO_CONSTANTS_2 = MUSIC_HERO_CONSTANTS;
export const CANDY_CRUSH_CONSTANTS_2 = CANDY_CRUSH_CONSTANTS;
export const GEM_BLAST_CONSTANTS_2 = GEM_BLAST_CONSTANTS;
export const BUBBLE_POP_CONSTANTS_2 = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_CONSTANTS_2 = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_CONSTANTS_2 = ANIMAL_MATCH_CONSTANTS;
export const BOWLING_MASTER_CONSTANTS_2 = BOWLING_MASTER_CONSTANTS;
export const ANGRY_BIRDS_CONSTANTS_2 = ANGRY_BIRDS_CONSTANTS;
export const DOODLE_JUMP_CONSTANTS_2 = DOODLE_JUMP_CONSTANTS;
export const PINBALL_PHYSICS_CONSTANTS_2 = PINBALL_PHYSICS_CONSTANTS;
export const CUT_ROPE_CONSTANTS_2 = CUT_ROPE_CONSTANTS;
export const PIXEL_FIGHTER_CONSTANTS_2 = PIXEL_FIGHTER_CONSTANTS;
export const BRAWL_STARS_CONSTANTS_2 = BRAWL_STARS_CONSTANTS;
export const KARATE_CHAMP_CONSTANTS_2 = KARATE_CHAMP_CONSTANTS;
export const SAMURAI_SLASH_CONSTANTS_2 = SAMURAI_SLASH_CONSTANTS;
export const WRESTLE_MANIA_CONSTANTS_2 = WRESTLE_MANIA_CONSTANTS;
export const NUMBER_SLIDE_CONSTANTS_2 = NUMBER_SLIDE_CONSTANTS;
export const PIPE_CONNECT_CONSTANTS_2 = PIPE_CONNECT_CONSTANTS;
export const MEMORY_MATCH_CONSTANTS_2 = MEMORY_MATCH_CONSTANTS;
export const WORD_SEARCH_CONSTANTS_2 = WORD_SEARCH_CONSTANTS;
export const VIRTUAL_PET_CONSTANTS_2 = VIRTUAL_PET_CONSTANTS;
export const GARDEN_GARDEN_CONSTANTS_2 = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_CONSTANTS_2 = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_CONSTANTS_2 = POKEMON_CONSTANTS;
export const BUBBLE_SHOOTER_CONSTANTS_2 = BUBBLE_SHOOTER_CONSTANTS;

// Engine constants with _2 suffix
export const SPACE_SHOOTER_ENGINE_CONSTANTS_2 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_ENGINE_CONSTANTS_2 = TANK_BATTLE_CONSTANTS;
export const ZOMBIE_SHOOTER_ENGINE_CONSTANTS_2 = ZOMBIE_SHOOTER_CONSTANTS;
export const FISH_TANK_ENGINE_CONSTANTS_2 = FISH_TANK_CONSTANTS;
export const PINBALL_DUO_ENGINE_CONSTANTS_2 = PINBALL_DUO_CONSTANTS;
export const BUNNY_HUNTER_ENGINE_CONSTANTS_2 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_ENGINE_CONSTANTS_2 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_ENGINE_CONSTANTS_2 = SNAKE_DUO_CONSTANTS;
export const BUBBLE_SHOOTER_ENGINE_CONSTANTS_2 = BUBBLE_SHOOTER_CONSTANTS;
export const THUNDER_ENGINE_CONSTANTS_2 = THUNDER_CONSTANTS;
export const MONOPOLY_ENGINE_CONSTANTS_2 = MONOPOLY_CONSTANTS;
export const HAPPY_FARM_ENGINE_CONSTANTS_2 = HAPPY_FARM_CONSTANTS;
export const COOKING_MASTER_ENGINE_CONSTANTS_2 = COOKING_MASTER_CONSTANTS;
export const SHOP_MASTER_ENGINE_CONSTANTS_2 = SHOP_MASTER_CONSTANTS;
export const FRUIT_NINJA_ENGINE_CONSTANTS_2 = FRUIT_NINJA_CONSTANTS;
export const WHACK_A_MOLE_ENGINE_CONSTANTS_2 = WHACK_A_MOLE_CONSTANTS;
export const COLOR_MATCH_ENGINE_CONSTANTS_2 = COLOR_MATCH_CONSTANTS;
export const BRAIN_TEST_ENGINE_CONSTANTS_2 = BRAIN_TEST_CONSTANTS;
export const CHESS_ENGINE_CONSTANTS_2 = CHESS_CONSTANTS;
export const GOBANG_ENGINE_CONSTANTS_2 = GOBANG_CONSTANTS;
export const LUDO_ENGINE_CONSTANTS_2 = LUDO_CONSTANTS;
export const TOWER_DEFENSE_ENGINE_CONSTANTS_2 = TOWER_DEFENSE_CONSTANTS;
export const CATAPULT_DEFENSE_ENGINE_CONSTANTS_2 = CATAPULT_DEFENSE_CONSTANTS;
export const MAGIC_TOWER_ENGINE_CONSTANTS_2 = MAGIC_TOWER_CONSTANTS;
export const DESERT_WAR_ENGINE_CONSTANTS_2 = DESERT_WAR_CONSTANTS;
export const ICE_AGE_DEFENSE_ENGINE_CONSTANTS_2 = ICE_AGE_DEFENSE_CONSTANTS;
export const RHYTHM_MASTER_ENGINE_CONSTANTS_2 = RHYTHM_MASTER_CONSTANTS;
export const DJ_MIXER_ENGINE_CONSTANTS_2 = DJ_MIXER_CONSTANTS;
export const PIANO_TILES_ENGINE_CONSTANTS_2 = PIANO_TILES_CONSTANTS;
export const BEAT_RACER_ENGINE_CONSTANTS_2 = BEAT_RACER_CONSTANTS;
export const MUSIC_HERO_ENGINE_CONSTANTS_2 = MUSIC_HERO_CONSTANTS;
export const CANDY_CRUSH_ENGINE_CONSTANTS_2 = CANDY_CRUSH_CONSTANTS;
export const GEM_BLAST_ENGINE_CONSTANTS_2 = GEM_BLAST_CONSTANTS;
export const BUBBLE_POP_ENGINE_CONSTANTS_2 = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_ENGINE_CONSTANTS_2 = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_ENGINE_CONSTANTS_2 = ANIMAL_MATCH_CONSTANTS;
export const BOWLING_MASTER_ENGINE_CONSTANTS_2 = BOWLING_MASTER_CONSTANTS;
export const ANGRY_BIRDS_ENGINE_CONSTANTS_2 = ANGRY_BIRDS_CONSTANTS;
export const DOODLE_JUMP_ENGINE_CONSTANTS_2 = DOODLE_JUMP_CONSTANTS;
export const PINBALL_PHYSICS_ENGINE_CONSTANTS_2 = PINBALL_PHYSICS_CONSTANTS;
export const CUT_ROPE_ENGINE_CONSTANTS_2 = CUT_ROPE_CONSTANTS;
export const PIXEL_FIGHTER_ENGINE_CONSTANTS_2 = PIXEL_FIGHTER_CONSTANTS;
export const BRAWL_STARS_ENGINE_CONSTANTS_2 = BRAWL_STARS_CONSTANTS;
export const KARATE_CHAMP_ENGINE_CONSTANTS_2 = KARATE_CHAMP_CONSTANTS;
export const SAMURAI_SLASH_ENGINE_CONSTANTS_2 = SAMURAI_SLASH_CONSTANTS;
export const WRESTLE_MANIA_ENGINE_CONSTANTS_2 = WRESTLE_MANIA_CONSTANTS;
export const HUARONG_DAO_ENGINE_CONSTANTS_2 = HUARONG_DAO_CONSTANTS;
export const NUMBER_SLIDE_ENGINE_CONSTANTS_2 = NUMBER_SLIDE_CONSTANTS;
export const PIPE_CONNECT_ENGINE_CONSTANTS_2 = PIPE_CONNECT_CONSTANTS;
export const MEMORY_MATCH_ENGINE_CONSTANTS_2 = MEMORY_MATCH_CONSTANTS;
export const WORD_SEARCH_ENGINE_CONSTANTS_2 = WORD_SEARCH_CONSTANTS;
export const VIRTUAL_PET_ENGINE_CONSTANTS_2 = VIRTUAL_PET_CONSTANTS;
export const GARDEN_GARDEN_ENGINE_CONSTANTS_2 = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_ENGINE_CONSTANTS_2 = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_ENGINE_CONSTANTS_2 = POKEMON_CONSTANTS;
export const HUARONG_DAO_CONSTANTS_3 = HUARONG_DAO_CONSTANTS;
export const NUMBER_SLIDE_CONSTANTS_3 = NUMBER_SLIDE_CONSTANTS;
export const PIPE_CONNECT_CONSTANTS_3 = PIPE_CONNECT_CONSTANTS;
export const MEMORY_MATCH_CONSTANTS_3 = MEMORY_MATCH_CONSTANTS;
export const WORD_SEARCH_CONSTANTS_3 = WORD_SEARCH_CONSTANTS;
export const VIRTUAL_PET_CONSTANTS_3 = VIRTUAL_PET_CONSTANTS;
export const FISH_TANK_CONSTANTS_3 = FISH_TANK_CONSTANTS;
export const GARDEN_GARDEN_CONSTANTS_3 = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_CONSTANTS_3 = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_CONSTANTS_3 = POKEMON_CONSTANTS;
export const BUBBLE_POP_CONSTANTS_3 = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_CONSTANTS_3 = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_CONSTANTS_3 = ANIMAL_MATCH_CONSTANTS;
export const BUBBLE_SHOOTER_CONSTANTS_3 = BUBBLE_SHOOTER_CONSTANTS;
export const BILLIARDS_CONSTANTS_3 = BILLIARDS_CONSTANTS;
export const BOUNCE_CONSTANTS_3 = BOUNCE_CONSTANTS;
export const BOWLING_CONSTANTS_3 = BOWLING_CONSTANTS;
export const PINBALL_CONSTANTS_3 = PINBALL_CONSTANTS;
export const ENHANCED_BREAKOUT_CONSTANTS_3 = ENHANCED_BREAKOUT_CONSTANTS;
export const DANCING_LINE_CONSTANTS_3 = DANCING_LINE_CONSTANTS;
export const CLIFF_RUNNER_CONSTANTS_3 = CLIFF_RUNNER_CONSTANTS;
export const COOP_RUN_CONSTANTS_3 = COOP_RUN_CONSTANTS;
export const TETRIS_CONSTANTS_3 = TETRIS_CONSTANTS;
export const SNAKE_CONSTANTS_3 = SNAKE_CONSTANTS;
export const MINESWEEPER_CONSTANTS_3 = MINESWEEPER_CONSTANTS;
export const BEJEWEL_CONSTANTS_3 = BEJEWEL_CONSTANTS;
export const SUDOKU_CONSTANTS_3 = SUDOKU_CONSTANTS;
export const FIRE_ICE_CONSTANTS_3 = FIRE_ICE_CONSTANTS;
export const GOLD_MINER_CONSTANTS_3 = GOLD_MINER_CONSTANTS;
export const FLAPPY_BIRD_CONSTANTS_3 = FLAPPY_BIRD_CONSTANTS;
export const PACMAN_CONSTANTS_3 = PACMAN_CONSTANTS;
export const STICKMAN_HOOK_CONSTANTS_3 = STICKMAN_HOOK_CONSTANTS;
export const HEXGL_CONSTANTS_3 = HEXGL_CONSTANTS;
export const TEMPLE_RUN_CONSTANTS_3 = TEMPLE_RUN_CONSTANTS;
export const ONEVONE_CONSTANTS_3 = ONEVONE_CONSTANTS;
export const CROSSCODE_CONSTANTS_3 = CROSSCODE_CONSTANTS;
export const ZUMA_CONSTANTS_3 = ZUMA_CONSTANTS;
export const SOKOBAN_CONSTANTS_3 = SOKOBAN_CONSTANTS;
export const RINGTOSS_CONSTANTS_3 = RINGTOSS_CONSTANTS;
export const SKIING_CONSTANTS_3 = SKIING_CONSTANTS;
export const SPEED_ESCAPE_CONSTANTS_3 = SPEED_ESCAPE_CONSTANTS;
export const SPACE_SHOOTER_CONSTANTS_3 = SPACE_SHOOTER_CONSTANTS;
export const ZOMBIE_SHOOTER_CONSTANTS_3 = ZOMBIE_SHOOTER_CONSTANTS;
export const FISH_TANK_CONSTANTS_4 = FISH_TANK_CONSTANTS;
export const PINBALL_DUO_CONSTANTS_3 = PINBALL_DUO_CONSTANTS;
export const BUNNY_HUNTER_CONSTANTS_3 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_CONSTANTS_3 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_CONSTANTS_3 = SNAKE_DUO_CONSTANTS;
export const SPACE_SHOOTER_CONSTANTS_4 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_CONSTANTS_3 = TANK_BATTLE_CONSTANTS;
export const BUBBLE_SHOOTER_ENGINE_CONSTANTS_3 = BUBBLE_SHOOTER_CONSTANTS;
export const THUNDER_ENGINE_CONSTANTS_3 = THUNDER_CONSTANTS;
export const MONOPOLY_ENGINE_CONSTANTS_3 = MONOPOLY_CONSTANTS;
export const HAPPY_FARM_ENGINE_CONSTANTS_3 = HAPPY_FARM_CONSTANTS;
export const COOKING_MASTER_ENGINE_CONSTANTS_3 = COOKING_MASTER_CONSTANTS;
export const SHOP_MASTER_ENGINE_CONSTANTS_3 = SHOP_MASTER_CONSTANTS;
export const FRUIT_NINJA_ENGINE_CONSTANTS_3 = FRUIT_NINJA_CONSTANTS;
export const WHACK_A_MOLE_ENGINE_CONSTANTS_3 = WHACK_A_MOLE_CONSTANTS;
export const COLOR_MATCH_ENGINE_CONSTANTS_3 = COLOR_MATCH_CONSTANTS;
export const BRAIN_TEST_ENGINE_CONSTANTS_3 = BRAIN_TEST_CONSTANTS;
export const CHESS_ENGINE_CONSTANTS_3 = CHESS_CONSTANTS;
export const GOBANG_ENGINE_CONSTANTS_3 = GOBANG_CONSTANTS;
export const LUDO_ENGINE_CONSTANTS_3 = LUDO_CONSTANTS;
export const TOWER_DEFENSE_ENGINE_CONSTANTS_3 = TOWER_DEFENSE_CONSTANTS;
export const CATAPULT_DEFENSE_ENGINE_CONSTANTS_3 = CATAPULT_DEFENSE_CONSTANTS;
export const MAGIC_TOWER_ENGINE_CONSTANTS_3 = MAGIC_TOWER_CONSTANTS;
export const DESERT_WAR_ENGINE_CONSTANTS_3 = DESERT_WAR_CONSTANTS;
export const ICE_AGE_DEFENSE_ENGINE_CONSTANTS_3 = ICE_AGE_DEFENSE_CONSTANTS;
export const RHYTHM_MASTER_ENGINE_CONSTANTS_3 = RHYTHM_MASTER_CONSTANTS;
export const DJ_MIXER_ENGINE_CONSTANTS_3 = DJ_MIXER_CONSTANTS;
export const PIANO_TILES_ENGINE_CONSTANTS_3 = PIANO_TILES_CONSTANTS;
export const BEAT_RACER_ENGINE_CONSTANTS_3 = BEAT_RACER_CONSTANTS;
export const MUSIC_HERO_ENGINE_CONSTANTS_3 = MUSIC_HERO_CONSTANTS;
export const CANDY_CRUSH_ENGINE_CONSTANTS_3 = CANDY_CRUSH_CONSTANTS;
export const GEM_BLAST_ENGINE_CONSTANTS_3 = GEM_BLAST_CONSTANTS;
export const BOWLING_MASTER_ENGINE_CONSTANTS_3 = BOWLING_MASTER_CONSTANTS;
export const ANGRY_BIRDS_ENGINE_CONSTANTS_3 = ANGRY_BIRDS_CONSTANTS;
export const DOODLE_JUMP_ENGINE_CONSTANTS_3 = DOODLE_JUMP_CONSTANTS;
export const PINBALL_PHYSICS_ENGINE_CONSTANTS_3 = PINBALL_PHYSICS_CONSTANTS;
export const CUT_ROPE_ENGINE_CONSTANTS_3 = CUT_ROPE_CONSTANTS;
export const PIXEL_FIGHTER_ENGINE_CONSTANTS_3 = PIXEL_FIGHTER_CONSTANTS;
export const BRAWL_STARS_ENGINE_CONSTANTS_3 = BRAWL_STARS_CONSTANTS;
export const KARATE_CHAMP_ENGINE_CONSTANTS_3 = KARATE_CHAMP_CONSTANTS;
export const SAMURAI_SLASH_ENGINE_CONSTANTS_3 = SAMURAI_SLASH_CONSTANTS;
export const WRESTLE_MANIA_ENGINE_CONSTANTS_3 = WRESTLE_MANIA_CONSTANTS;
export const HUARONG_DAO_ENGINE_CONSTANTS_3 = HUARONG_DAO_CONSTANTS;
export const NUMBER_SLIDE_ENGINE_CONSTANTS_3 = NUMBER_SLIDE_CONSTANTS;
export const PIPE_CONNECT_ENGINE_CONSTANTS_3 = PIPE_CONNECT_CONSTANTS;
export const MEMORY_MATCH_ENGINE_CONSTANTS_3 = MEMORY_MATCH_CONSTANTS;
export const WORD_SEARCH_ENGINE_CONSTANTS_3 = WORD_SEARCH_CONSTANTS;
export const VIRTUAL_PET_ENGINE_CONSTANTS_3 = VIRTUAL_PET_CONSTANTS;
export const FISH_TANK_ENGINE_CONSTANTS_3 = FISH_TANK_CONSTANTS;
export const GARDEN_GARDEN_ENGINE_CONSTANTS_3 = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_ENGINE_CONSTANTS_3 = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_ENGINE_CONSTANTS_3 = POKEMON_CONSTANTS;
export const BUBBLE_POP_ENGINE_CONSTANTS_3 = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_ENGINE_CONSTANTS_3 = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_ENGINE_CONSTANTS_3 = ANIMAL_MATCH_CONSTANTS;
export const BUBBLE_SHOOTER_ENGINE_CONSTANTS_4 = BUBBLE_SHOOTER_CONSTANTS;
export const BUNNY_HUNTER_ENGINE_CONSTANTS_3 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_ENGINE_CONSTANTS_3 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_ENGINE_CONSTANTS_3 = SNAKE_DUO_CONSTANTS;
export const PINBALL_DUO_ENGINE_CONSTANTS_3 = PINBALL_DUO_CONSTANTS;
export const SPACE_SHOOTER_ENGINE_CONSTANTS_3 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_ENGINE_CONSTANTS_3 = TANK_BATTLE_CONSTANTS;
export const ZOMBIE_SHOOTER_ENGINE_CONSTANTS_3 = ZOMBIE_SHOOTER_CONSTANTS;
export const BOWLING_MASTER_ENGINE_CONSTANTS_4 = BOWLING_MASTER_CONSTANTS;
export const ANGRY_BIRDS_ENGINE_CONSTANTS_4 = ANGRY_BIRDS_CONSTANTS;
export const DOODLE_JUMP_ENGINE_CONSTANTS_4 = DOODLE_JUMP_CONSTANTS;
export const PINBALL_PHYSICS_ENGINE_CONSTANTS_4 = PINBALL_PHYSICS_CONSTANTS;
export const CUT_ROPE_ENGINE_CONSTANTS_4 = CUT_ROPE_CONSTANTS;
export const HUARONG_DAO_ENGINE_CONSTANTS_4 = HUARONG_DAO_CONSTANTS;
export const NUMBER_SLIDE_ENGINE_CONSTANTS_4 = NUMBER_SLIDE_CONSTANTS;
export const PIPE_CONNECT_ENGINE_CONSTANTS_4 = PIPE_CONNECT_CONSTANTS;
export const MEMORY_MATCH_ENGINE_CONSTANTS_4 = MEMORY_MATCH_CONSTANTS;
export const WORD_SEARCH_ENGINE_CONSTANTS_4 = WORD_SEARCH_CONSTANTS;
export const VIRTUAL_PET_ENGINE_CONSTANTS_4 = VIRTUAL_PET_CONSTANTS;
export const FISH_TANK_ENGINE_CONSTANTS_4 = FISH_TANK_CONSTANTS;
export const GARDEN_GARDEN_ENGINE_CONSTANTS_4 = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_ENGINE_CONSTANTS_4 = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_ENGINE_CONSTANTS_4 = POKEMON_CONSTANTS;
export const BUBBLE_POP_ENGINE_CONSTANTS_4 = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_ENGINE_CONSTANTS_4 = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_ENGINE_CONSTANTS_4 = ANIMAL_MATCH_CONSTANTS;
export const BUNNY_HUNTER_ENGINE_CONSTANTS_4 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_ENGINE_CONSTANTS_4 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_ENGINE_CONSTANTS_4 = SNAKE_DUO_CONSTANTS;
export const PINBALL_DUO_ENGINE_CONSTANTS_4 = PINBALL_DUO_CONSTANTS;
export const SPACE_SHOOTER_ENGINE_CONSTANTS_4 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_ENGINE_CONSTANTS_4 = TANK_BATTLE_CONSTANTS;
export const ZOMBIE_SHOOTER_ENGINE_CONSTANTS_4 = ZOMBIE_SHOOTER_CONSTANTS;
export const ANGRY_BIRDS_ENGINE_CONSTANTS_5 = ANGRY_BIRDS_CONSTANTS;
export const DOODLE_JUMP_ENGINE_CONSTANTS_5 = DOODLE_JUMP_CONSTANTS;
export const BOWLING_MASTER_ENGINE_CONSTANTS_5 = BOWLING_MASTER_CONSTANTS;
export const PINBALL_PHYSICS_ENGINE_CONSTANTS_5 = PINBALL_PHYSICS_CONSTANTS;
export const CUT_ROPE_ENGINE_CONSTANTS_5 = CUT_ROPE_CONSTANTS;
export const HUARONG_DAO_ENGINE_CONSTANTS_5 = HUARONG_DAO_CONSTANTS;
export const NUMBER_SLIDE_ENGINE_CONSTANTS_5 = NUMBER_SLIDE_CONSTANTS;
export const PIPE_CONNECT_ENGINE_CONSTANTS_5 = PIPE_CONNECT_CONSTANTS;
export const MEMORY_MATCH_ENGINE_CONSTANTS_5 = MEMORY_MATCH_CONSTANTS;
export const WORD_SEARCH_ENGINE_CONSTANTS_5 = WORD_SEARCH_CONSTANTS;
export const VIRTUAL_PET_ENGINE_CONSTANTS_5 = VIRTUAL_PET_CONSTANTS;
export const FISH_TANK_ENGINE_CONSTANTS_5 = FISH_TANK_CONSTANTS;
export const GARDEN_GARDEN_ENGINE_CONSTANTS_5 = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_ENGINE_CONSTANTS_5 = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_ENGINE_CONSTANTS_5 = POKEMON_CONSTANTS;
export const BUBBLE_POP_ENGINE_CONSTANTS_5 = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_ENGINE_CONSTANTS_5 = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_ENGINE_CONSTANTS_5 = ANIMAL_MATCH_CONSTANTS;
export const BUNNY_HUNTER_ENGINE_CONSTANTS_5 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_ENGINE_CONSTANTS_5 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_ENGINE_CONSTANTS_5 = SNAKE_DUO_CONSTANTS;
export const PINBALL_DUO_ENGINE_CONSTANTS_5 = PINBALL_DUO_CONSTANTS;
export const SPACE_SHOOTER_ENGINE_CONSTANTS_5 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_ENGINE_CONSTANTS_5 = TANK_BATTLE_CONSTANTS;
export const ZOMBIE_SHOOTER_ENGINE_CONSTANTS_5 = ZOMBIE_SHOOTER_CONSTANTS;
export const BUBBLE_SHOOTER_CONSTANTS_4 = BUBBLE_SHOOTER_CONSTANTS;
export const BILLIARDS_CONSTANTS_4 = BILLIARDS_CONSTANTS;
export const BOUNCE_CONSTANTS_4 = BOUNCE_CONSTANTS;
export const BOWLING_CONSTANTS_4 = BOWLING_CONSTANTS;
export const PINBALL_CONSTANTS_4 = PINBALL_CONSTANTS;
export const ENHANCED_BREAKOUT_CONSTANTS_4 = ENHANCED_BREAKOUT_CONSTANTS;
export const DANCING_LINE_CONSTANTS_4 = DANCING_LINE_CONSTANTS;
export const CLIFF_RUNNER_CONSTANTS_4 = CLIFF_RUNNER_CONSTANTS;
export const COOP_RUN_CONSTANTS_4 = COOP_RUN_CONSTANTS;
export const TETRIS_CONSTANTS_4 = TETRIS_CONSTANTS;
export const SNAKE_CONSTANTS_4 = SNAKE_CONSTANTS;
export const MINESWEEPER_CONSTANTS_4 = MINESWEEPER_CONSTANTS;
export const BEJEWEL_CONSTANTS_4 = BEJEWEL_CONSTANTS;
export const SUDOKU_CONSTANTS_4 = SUDOKU_CONSTANTS;
export const FIRE_ICE_CONSTANTS_4 = FIRE_ICE_CONSTANTS;
export const GOLD_MINER_CONSTANTS_4 = GOLD_MINER_CONSTANTS;
export const FLAPPY_BIRD_CONSTANTS_4 = FLAPPY_BIRD_CONSTANTS;
export const PACMAN_CONSTANTS_4 = PACMAN_CONSTANTS;
export const STICKMAN_HOOK_CONSTANTS_4 = STICKMAN_HOOK_CONSTANTS;
export const HEXGL_CONSTANTS_4 = HEXGL_CONSTANTS;
export const TEMPLE_RUN_CONSTANTS_4 = TEMPLE_RUN_CONSTANTS;
export const ONEVONE_CONSTANTS_4 = ONEVONE_CONSTANTS;
export const CROSSCODE_CONSTANTS_4 = CROSSCODE_CONSTANTS;
export const ZUMA_CONSTANTS_4 = ZUMA_CONSTANTS;
export const SOKOBAN_CONSTANTS_4 = SOKOBAN_CONSTANTS;
export const RINGTOSS_CONSTANTS_4 = RINGTOSS_CONSTANTS;
export const SKIING_CONSTANTS_4 = SKIING_CONSTANTS;
export const SPEED_ESCAPE_CONSTANTS_4 = SPEED_ESCAPE_CONSTANTS;
export const SPACE_SHOOTER_CONSTANTS_5 = SPACE_SHOOTER_CONSTANTS;
export const ZOMBIE_SHOOTER_CONSTANTS_4 = ZOMBIE_SHOOTER_CONSTANTS;
export const FISH_TANK_CONSTANTS_5 = FISH_TANK_CONSTANTS;
export const PINBALL_DUO_CONSTANTS_4 = PINBALL_DUO_CONSTANTS;
export const BUNNY_HUNTER_CONSTANTS_4 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_CONSTANTS_4 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_CONSTANTS_4 = SNAKE_DUO_CONSTANTS;
export const SPACE_SHOOTER_CONSTANTS_6 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_CONSTANTS_4 = TANK_BATTLE_CONSTANTS;
export const BUBBLE_SHOOTER_ENGINE_CONSTANTS_5 = BUBBLE_SHOOTER_CONSTANTS;
export const THUNDER_ENGINE_CONSTANTS_4 = THUNDER_CONSTANTS;
export const MONOPOLY_ENGINE_CONSTANTS_4 = MONOPOLY_CONSTANTS;
export const HAPPY_FARM_ENGINE_CONSTANTS_4 = HAPPY_FARM_CONSTANTS;
export const COOKING_MASTER_ENGINE_CONSTANTS_4 = COOKING_MASTER_CONSTANTS;
export const SHOP_MASTER_ENGINE_CONSTANTS_4 = SHOP_MASTER_CONSTANTS;
export const FRUIT_NINJA_ENGINE_CONSTANTS_4 = FRUIT_NINJA_CONSTANTS;
export const WHACK_A_MOLE_ENGINE_CONSTANTS_4 = WHACK_A_MOLE_CONSTANTS;
export const COLOR_MATCH_ENGINE_CONSTANTS_4 = COLOR_MATCH_CONSTANTS;
export const BRAIN_TEST_ENGINE_CONSTANTS_4 = BRAIN_TEST_CONSTANTS;
export const CHESS_ENGINE_CONSTANTS_4 = CHESS_CONSTANTS;
export const GOBANG_ENGINE_CONSTANTS_4 = GOBANG_CONSTANTS;
export const LUDO_ENGINE_CONSTANTS_4 = LUDO_CONSTANTS;
export const TOWER_DEFENSE_ENGINE_CONSTANTS_4 = TOWER_DEFENSE_CONSTANTS;
export const CATAPULT_DEFENSE_ENGINE_CONSTANTS_4 = CATAPULT_DEFENSE_CONSTANTS;
export const MAGIC_TOWER_ENGINE_CONSTANTS_4 = MAGIC_TOWER_CONSTANTS;
export const DESERT_WAR_ENGINE_CONSTANTS_4 = DESERT_WAR_CONSTANTS;
export const ICE_AGE_DEFENSE_ENGINE_CONSTANTS_4 = ICE_AGE_DEFENSE_CONSTANTS;
export const RHYTHM_MASTER_ENGINE_CONSTANTS_4 = RHYTHM_MASTER_CONSTANTS;
export const DJ_MIXER_ENGINE_CONSTANTS_4 = DJ_MIXER_CONSTANTS;
export const PIANO_TILES_ENGINE_CONSTANTS_4 = PIANO_TILES_CONSTANTS;
export const BEAT_RACER_ENGINE_CONSTANTS_4 = BEAT_RACER_CONSTANTS;
export const MUSIC_HERO_ENGINE_CONSTANTS_4 = MUSIC_HERO_CONSTANTS;
export const CANDY_CRUSH_ENGINE_CONSTANTS_4 = CANDY_CRUSH_CONSTANTS;
export const GEM_BLAST_ENGINE_CONSTANTS_4 = GEM_BLAST_CONSTANTS;
export const BOWLING_MASTER_ENGINE_CONSTANTS_6 = BOWLING_MASTER_CONSTANTS;
export const ANGRY_BIRDS_ENGINE_CONSTANTS_6 = ANGRY_BIRDS_CONSTANTS;
export const DOODLE_JUMP_ENGINE_CONSTANTS_6 = DOODLE_JUMP_CONSTANTS;
export const PINBALL_PHYSICS_ENGINE_CONSTANTS_6 = PINBALL_PHYSICS_CONSTANTS;
export const CUT_ROPE_ENGINE_CONSTANTS_6 = CUT_ROPE_CONSTANTS;
export const PIXEL_FIGHTER_ENGINE_CONSTANTS_4 = PIXEL_FIGHTER_CONSTANTS;
export const BRAWL_STARS_ENGINE_CONSTANTS_4 = BRAWL_STARS_CONSTANTS;
export const KARATE_CHAMP_ENGINE_CONSTANTS_4 = KARATE_CHAMP_CONSTANTS;
export const SAMURAI_SLASH_ENGINE_CONSTANTS_4 = SAMURAI_SLASH_CONSTANTS;
export const WRESTLE_MANIA_ENGINE_CONSTANTS_4 = WRESTLE_MANIA_CONSTANTS;
export const VIRTUAL_PET_ENGINE_CONSTANTS_6 = VIRTUAL_PET_CONSTANTS;
export const FISH_TANK_ENGINE_CONSTANTS_6 = FISH_TANK_CONSTANTS;
export const GARDEN_GARDEN_ENGINE_CONSTANTS_6 = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_ENGINE_CONSTANTS_6 = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_ENGINE_CONSTANTS_6 = POKEMON_CONSTANTS;
export const BUBBLE_POP_ENGINE_CONSTANTS_6 = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_ENGINE_CONSTANTS_6 = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_ENGINE_CONSTANTS_6 = ANIMAL_MATCH_CONSTANTS;
export const BUNNY_HUNTER_ENGINE_CONSTANTS_6 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_ENGINE_CONSTANTS_6 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_ENGINE_CONSTANTS_6 = SNAKE_DUO_CONSTANTS;
export const PINBALL_DUO_ENGINE_CONSTANTS_6 = PINBALL_DUO_CONSTANTS;
export const SPACE_SHOOTER_ENGINE_CONSTANTS_6 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_ENGINE_CONSTANTS_6 = TANK_BATTLE_CONSTANTS;
export const ZOMBIE_SHOOTER_ENGINE_CONSTANTS_6 = ZOMBIE_SHOOTER_CONSTANTS;
export const BUBBLE_SHOOTER_CONSTANTS_5 = BUBBLE_SHOOTER_CONSTANTS;
export const BILLIARDS_CONSTANTS_5 = BILLIARDS_CONSTANTS;
export const BOUNCE_CONSTANTS_5 = BOUNCE_CONSTANTS;
export const BOWLING_CONSTANTS_5 = BOWLING_CONSTANTS;
export const PINBALL_CONSTANTS_5 = PINBALL_CONSTANTS;
export const ENHANCED_BREAKOUT_CONSTANTS_5 = ENHANCED_BREAKOUT_CONSTANTS;
export const DANCING_LINE_CONSTANTS_5 = DANCING_LINE_CONSTANTS;
export const CLIFF_RUNNER_CONSTANTS_5 = CLIFF_RUNNER_CONSTANTS;
export const COOP_RUN_CONSTANTS_5 = COOP_RUN_CONSTANTS;
export const TETRIS_CONSTANTS_5 = TETRIS_CONSTANTS;
export const SNAKE_CONSTANTS_5 = SNAKE_CONSTANTS;
export const MINESWEEPER_CONSTANTS_5 = MINESWEEPER_CONSTANTS;
export const BEJEWEL_CONSTANTS_5 = BEJEWEL_CONSTANTS;
export const SUDOKU_CONSTANTS_5 = SUDOKU_CONSTANTS;
export const FIRE_ICE_CONSTANTS_5 = FIRE_ICE_CONSTANTS;
export const GOLD_MINER_CONSTANTS_5 = GOLD_MINER_CONSTANTS;
export const FLAPPY_BIRD_CONSTANTS_5 = FLAPPY_BIRD_CONSTANTS;
export const PACMAN_CONSTANTS_5 = PACMAN_CONSTANTS;
export const STICKMAN_HOOK_CONSTANTS_5 = STICKMAN_HOOK_CONSTANTS;
export const HEXGL_CONSTANTS_5 = HEXGL_CONSTANTS;
export const TEMPLE_RUN_CONSTANTS_5 = TEMPLE_RUN_CONSTANTS;
export const ONEVONE_CONSTANTS_5 = ONEVONE_CONSTANTS;
export const CROSSCODE_CONSTANTS_5 = CROSSCODE_CONSTANTS;
export const ZUMA_CONSTANTS_5 = ZUMA_CONSTANTS;
export const SOKOBAN_CONSTANTS_5 = SOKOBAN_CONSTANTS;
export const RINGTOSS_CONSTANTS_5 = RINGTOSS_CONSTANTS;
export const SKIING_CONSTANTS_5 = SKIING_CONSTANTS;
export const SPEED_ESCAPE_CONSTANTS_5 = SPEED_ESCAPE_CONSTANTS;
export const SPACE_SHOOTER_CONSTANTS_7 = SPACE_SHOOTER_CONSTANTS;
export const ZOMBIE_SHOOTER_CONSTANTS_5 = ZOMBIE_SHOOTER_CONSTANTS;
export const FISH_TANK_CONSTANTS_6 = FISH_TANK_CONSTANTS;
export const PINBALL_DUO_CONSTANTS_5 = PINBALL_DUO_CONSTANTS;
export const BUNNY_HUNTER_CONSTANTS_5 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_CONSTANTS_5 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_CONSTANTS_5 = SNAKE_DUO_CONSTANTS;
export const SPACE_SHOOTER_CONSTANTS_8 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_CONSTANTS_5 = TANK_BATTLE_CONSTANTS;
export const BUBBLE_SHOOTER_ENGINE_CONSTANTS_6 = BUBBLE_SHOOTER_CONSTANTS;
export const THUNDER_ENGINE_CONSTANTS_5 = THUNDER_CONSTANTS;
export const MONOPOLY_ENGINE_CONSTANTS_5 = MONOPOLY_CONSTANTS;
export const HAPPY_FARM_ENGINE_CONSTANTS_5 = HAPPY_FARM_CONSTANTS;
export const COOKING_MASTER_ENGINE_CONSTANTS_5 = COOKING_MASTER_CONSTANTS;
export const SHOP_MASTER_ENGINE_CONSTANTS_5 = SHOP_MASTER_CONSTANTS;
export const FRUIT_NINJA_ENGINE_CONSTANTS_5 = FRUIT_NINJA_CONSTANTS;
export const WHACK_A_MOLE_ENGINE_CONSTANTS_5 = WHACK_A_MOLE_CONSTANTS;
export const COLOR_MATCH_ENGINE_CONSTANTS_5 = COLOR_MATCH_CONSTANTS;
export const BRAIN_TEST_ENGINE_CONSTANTS_5 = BRAIN_TEST_CONSTANTS;
export const CHESS_ENGINE_CONSTANTS_5 = CHESS_CONSTANTS;
export const GOBANG_ENGINE_CONSTANTS_5 = GOBANG_CONSTANTS;
export const LUDO_ENGINE_CONSTANTS_5 = LUDO_CONSTANTS;
export const TOWER_DEFENSE_ENGINE_CONSTANTS_5 = TOWER_DEFENSE_CONSTANTS;
export const CATAPULT_DEFENSE_ENGINE_CONSTANTS_5 = CATAPULT_DEFENSE_CONSTANTS;
export const MAGIC_TOWER_ENGINE_CONSTANTS_5 = MAGIC_TOWER_CONSTANTS;
export const DESERT_WAR_ENGINE_CONSTANTS_5 = DESERT_WAR_CONSTANTS;
export const ICE_AGE_DEFENSE_ENGINE_CONSTANTS_5 = ICE_AGE_DEFENSE_CONSTANTS;
export const CANDY_CRUSH_ENGINE_CONSTANTS_5 = CANDY_CRUSH_CONSTANTS;
export const GEM_BLAST_ENGINE_CONSTANTS_5 = GEM_BLAST_CONSTANTS;
export const BOWLING_MASTER_ENGINE_CONSTANTS_7 = BOWLING_MASTER_CONSTANTS;
export const ANGRY_BIRDS_ENGINE_CONSTANTS_7 = ANGRY_BIRDS_CONSTANTS;
export const DOODLE_JUMP_ENGINE_CONSTANTS_7 = DOODLE_JUMP_CONSTANTS;
export const PINBALL_PHYSICS_ENGINE_CONSTANTS_7 = PINBALL_PHYSICS_CONSTANTS;
export const CUT_ROPE_ENGINE_CONSTANTS_7 = CUT_ROPE_CONSTANTS;
export const HUARONG_DAO_ENGINE_CONSTANTS_6 = HUARONG_DAO_CONSTANTS;
export const NUMBER_SLIDE_ENGINE_CONSTANTS_6 = NUMBER_SLIDE_CONSTANTS;
export const PIPE_CONNECT_ENGINE_CONSTANTS_6 = PIPE_CONNECT_CONSTANTS;
export const MEMORY_MATCH_ENGINE_CONSTANTS_6 = MEMORY_MATCH_CONSTANTS;
export const WORD_SEARCH_ENGINE_CONSTANTS_6 = WORD_SEARCH_CONSTANTS;
export const VIRTUAL_PET_ENGINE_CONSTANTS_7 = VIRTUAL_PET_CONSTANTS;
export const FISH_TANK_ENGINE_CONSTANTS_7 = FISH_TANK_CONSTANTS;
export const GARDEN_GARDEN_ENGINE_CONSTANTS_7 = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_ENGINE_CONSTANTS_7 = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_ENGINE_CONSTANTS_7 = POKEMON_CONSTANTS;
export const BUBBLE_POP_ENGINE_CONSTANTS_7 = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_ENGINE_CONSTANTS_7 = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_ENGINE_CONSTANTS_7 = ANIMAL_MATCH_CONSTANTS;
export const BUNNY_HUNTER_ENGINE_CONSTANTS_7 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_ENGINE_CONSTANTS_7 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_ENGINE_CONSTANTS_7 = SNAKE_DUO_CONSTANTS;
export const PINBALL_DUO_ENGINE_CONSTANTS_7 = PINBALL_DUO_CONSTANTS;
export const SPACE_SHOOTER_ENGINE_CONSTANTS_7 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_ENGINE_CONSTANTS_7 = TANK_BATTLE_CONSTANTS;
export const ZOMBIE_SHOOTER_ENGINE_CONSTANTS_7 = ZOMBIE_SHOOTER_CONSTANTS;
export const BUBBLE_SHOOTER_CONSTANTS_6 = BUBBLE_SHOOTER_CONSTANTS;
export const BILLIARDS_CONSTANTS_6 = BILLIARDS_CONSTANTS;
export const BOUNCE_CONSTANTS_6 = BOUNCE_CONSTANTS;
export const BOWLING_CONSTANTS_6 = BOWLING_CONSTANTS;
export const PINBALL_CONSTANTS_6 = PINBALL_CONSTANTS;
export const ENHANCED_BREAKOUT_CONSTANTS_6 = ENHANCED_BREAKOUT_CONSTANTS;
export const DANCING_LINE_CONSTANTS_6 = DANCING_LINE_CONSTANTS;
export const CLIFF_RUNNER_CONSTANTS_6 = CLIFF_RUNNER_CONSTANTS;
export const COOP_RUN_CONSTANTS_6 = COOP_RUN_CONSTANTS;
export const TETRIS_CONSTANTS_6 = TETRIS_CONSTANTS;
export const SNAKE_CONSTANTS_6 = SNAKE_CONSTANTS;
export const MINESWEEPER_CONSTANTS_6 = MINESWEEPER_CONSTANTS;
export const BEJEWEL_CONSTANTS_6 = BEJEWEL_CONSTANTS;
export const SUDOKU_CONSTANTS_6 = SUDOKU_CONSTANTS;
export const FIRE_ICE_CONSTANTS_6 = FIRE_ICE_CONSTANTS;
export const GOLD_MINER_CONSTANTS_6 = GOLD_MINER_CONSTANTS;
export const FLAPPY_BIRD_CONSTANTS_6 = FLAPPY_BIRD_CONSTANTS;
export const PACMAN_CONSTANTS_6 = PACMAN_CONSTANTS;
export const STICKMAN_HOOK_CONSTANTS_6 = STICKMAN_HOOK_CONSTANTS;
export const HEXGL_CONSTANTS_6 = HEXGL_CONSTANTS;
export const TEMPLE_RUN_CONSTANTS_6 = TEMPLE_RUN_CONSTANTS;
export const ONEVONE_CONSTANTS_6 = ONEVONE_CONSTANTS;
export const CROSSCODE_CONSTANTS_6 = CROSSCODE_CONSTANTS;
export const ZUMA_CONSTANTS_6 = ZUMA_CONSTANTS;
export const SOKOBAN_CONSTANTS_6 = SOKOBAN_CONSTANTS;
export const RINGTOSS_CONSTANTS_6 = RINGTOSS_CONSTANTS;
export const SKIING_CONSTANTS_6 = SKIING_CONSTANTS;
export const SPEED_ESCAPE_CONSTANTS_6 = SPEED_ESCAPE_CONSTANTS;
export const SPACE_SHOOTER_CONSTANTS_9 = SPACE_SHOOTER_CONSTANTS;
export const ZOMBIE_SHOOTER_CONSTANTS_6 = ZOMBIE_SHOOTER_CONSTANTS;
export const FISH_TANK_CONSTANTS_7 = FISH_TANK_CONSTANTS;
export const PINBALL_DUO_CONSTANTS_6 = PINBALL_DUO_CONSTANTS;
export const BUNNY_HUNTER_CONSTANTS_6 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_CONSTANTS_6 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_CONSTANTS_6 = SNAKE_DUO_CONSTANTS;
export const SPACE_SHOOTER_CONSTANTS_10 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_CONSTANTS_6 = TANK_BATTLE_CONSTANTS;
export const BUBBLE_SHOOTER_ENGINE_CONSTANTS_7 = BUBBLE_SHOOTER_CONSTANTS;
export const THUNDER_ENGINE_CONSTANTS_6 = THUNDER_CONSTANTS;
export const MONOPOLY_ENGINE_CONSTANTS_6 = MONOPOLY_CONSTANTS;
export const HAPPY_FARM_ENGINE_CONSTANTS_6 = HAPPY_FARM_CONSTANTS;
export const COOKING_MASTER_ENGINE_CONSTANTS_6 = COOKING_MASTER_CONSTANTS;
export const SHOP_MASTER_ENGINE_CONSTANTS_6 = SHOP_MASTER_CONSTANTS;
export const FRUIT_NINJA_ENGINE_CONSTANTS_6 = FRUIT_NINJA_CONSTANTS;
export const WHACK_A_MOLE_ENGINE_CONSTANTS_6 = WHACK_A_MOLE_CONSTANTS;
export const COLOR_MATCH_ENGINE_CONSTANTS_6 = COLOR_MATCH_CONSTANTS;
export const BRAIN_TEST_ENGINE_CONSTANTS_6 = BRAIN_TEST_CONSTANTS;
export const CHESS_ENGINE_CONSTANTS_6 = CHESS_CONSTANTS;
export const GOBANG_ENGINE_CONSTANTS_6 = GOBANG_CONSTANTS;
export const LUDO_ENGINE_CONSTANTS_6 = LUDO_CONSTANTS;
export const TOWER_DEFENSE_ENGINE_CONSTANTS_6 = TOWER_DEFENSE_CONSTANTS;
export const CATAPULT_DEFENSE_ENGINE_CONSTANTS_6 = CATAPULT_DEFENSE_CONSTANTS;
export const MAGIC_TOWER_ENGINE_CONSTANTS_6 = MAGIC_TOWER_CONSTANTS;
export const DESERT_WAR_ENGINE_CONSTANTS_6 = DESERT_WAR_CONSTANTS;
export const ICE_AGE_DEFENSE_ENGINE_CONSTANTS_6 = ICE_AGE_DEFENSE_CONSTANTS;
export const CANDY_CRUSH_ENGINE_CONSTANTS_6 = CANDY_CRUSH_CONSTANTS;
export const GEM_BLAST_ENGINE_CONSTANTS_6 = GEM_BLAST_CONSTANTS;
export const BOWLING_MASTER_ENGINE_CONSTANTS_8 = BOWLING_MASTER_CONSTANTS;
export const ANGRY_BIRDS_ENGINE_CONSTANTS_8 = ANGRY_BIRDS_CONSTANTS;
export const DOODLE_JUMP_ENGINE_CONSTANTS_8 = DOODLE_JUMP_CONSTANTS;
export const PINBALL_PHYSICS_ENGINE_CONSTANTS_8 = PINBALL_PHYSICS_CONSTANTS;
export const CUT_ROPE_ENGINE_CONSTANTS_8 = CUT_ROPE_CONSTANTS;
export const HUARONG_DAO_ENGINE_CONSTANTS_7 = HUARONG_DAO_CONSTANTS;
export const NUMBER_SLIDE_ENGINE_CONSTANTS_7 = NUMBER_SLIDE_CONSTANTS;
export const PIPE_CONNECT_ENGINE_CONSTANTS_7 = PIPE_CONNECT_CONSTANTS;
export const MEMORY_MATCH_ENGINE_CONSTANTS_7 = MEMORY_MATCH_CONSTANTS;
export const WORD_SEARCH_ENGINE_CONSTANTS_7 = WORD_SEARCH_CONSTANTS;
export const VIRTUAL_PET_ENGINE_CONSTANTS_8 = VIRTUAL_PET_CONSTANTS;
export const FISH_TANK_ENGINE_CONSTANTS_8 = FISH_TANK_CONSTANTS;
export const GARDEN_GARDEN_ENGINE_CONSTANTS_8 = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_ENGINE_CONSTANTS_8 = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_ENGINE_CONSTANTS_8 = POKEMON_CONSTANTS;
export const BUBBLE_POP_ENGINE_CONSTANTS_8 = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_ENGINE_CONSTANTS_8 = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_ENGINE_CONSTANTS_8 = ANIMAL_MATCH_CONSTANTS;
export const BUNNY_HUNTER_ENGINE_CONSTANTS_8 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_ENGINE_CONSTANTS_8 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_ENGINE_CONSTANTS_8 = SNAKE_DUO_CONSTANTS;
export const PINBALL_DUO_ENGINE_CONSTANTS_8 = PINBALL_DUO_CONSTANTS;
export const SPACE_SHOOTER_ENGINE_CONSTANTS_8 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_ENGINE_CONSTANTS_8 = TANK_BATTLE_CONSTANTS;
export const ZOMBIE_SHOOTER_ENGINE_CONSTANTS_8 = ZOMBIE_SHOOTER_CONSTANTS;
export const ANGRY_BIRDS_ENGINE_CONSTANTS_9 = ANGRY_BIRDS_CONSTANTS;
export const DOODLE_JUMP_ENGINE_CONSTANTS_9 = DOODLE_JUMP_CONSTANTS;
export const BOWLING_MASTER_ENGINE_CONSTANTS_9 = BOWLING_MASTER_CONSTANTS;
export const PINBALL_PHYSICS_ENGINE_CONSTANTS_9 = PINBALL_PHYSICS_CONSTANTS;
export const CUT_ROPE_ENGINE_CONSTANTS_9 = CUT_ROPE_CONSTANTS;
export const VIRTUAL_PET_ENGINE_CONSTANTS_9 = VIRTUAL_PET_CONSTANTS;
export const FISH_TANK_ENGINE_CONSTANTS_9 = FISH_TANK_CONSTANTS;
export const GARDEN_GARDEN_ENGINE_CONSTANTS_9 = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_ENGINE_CONSTANTS_9 = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_ENGINE_CONSTANTS_9 = POKEMON_CONSTANTS;
export const BUBBLE_POP_ENGINE_CONSTANTS_9 = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_ENGINE_CONSTANTS_9 = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_ENGINE_CONSTANTS_9 = ANIMAL_MATCH_CONSTANTS;
export const BUNNY_HUNTER_ENGINE_CONSTANTS_9 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_ENGINE_CONSTANTS_9 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_ENGINE_CONSTANTS_9 = SNAKE_DUO_CONSTANTS;
export const PINBALL_DUO_ENGINE_CONSTANTS_9 = PINBALL_DUO_CONSTANTS;
export const SPACE_SHOOTER_ENGINE_CONSTANTS_9 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_ENGINE_CONSTANTS_9 = TANK_BATTLE_CONSTANTS;
export const ZOMBIE_SHOOTER_ENGINE_CONSTANTS_9 = ZOMBIE_SHOOTER_CONSTANTS;
export const ANGRY_BIRDS_ENGINE_CONSTANTS_10 = ANGRY_BIRDS_CONSTANTS;
export const DOODLE_JUMP_ENGINE_CONSTANTS_10 = DOODLE_JUMP_CONSTANTS;
export const BOWLING_MASTER_ENGINE_CONSTANTS_10 = BOWLING_MASTER_CONSTANTS;
export const PINBALL_PHYSICS_ENGINE_CONSTANTS_10 = PINBALL_PHYSICS_CONSTANTS;
export const CUT_ROPE_ENGINE_CONSTANTS_10 = CUT_ROPE_CONSTANTS;
export const VIRTUAL_PET_ENGINE_CONSTANTS_10 = VIRTUAL_PET_CONSTANTS;
export const FISH_TANK_ENGINE_CONSTANTS_10 = FISH_TANK_CONSTANTS;
export const GARDEN_GARDEN_ENGINE_CONSTANTS_10 = GARDEN_GARDEN_CONSTANTS;
export const COOKIE_BAKERY_ENGINE_CONSTANTS_10 = COOKIE_BAKERY_CONSTANTS;
export const POKEMON_ENGINE_CONSTANTS_10 = POKEMON_CONSTANTS;
export const BUBBLE_POP_ENGINE_CONSTANTS_10 = BUBBLE_POP_CONSTANTS;
export const COOKIE_MATCH_ENGINE_CONSTANTS_10 = COOKIE_MATCH_CONSTANTS;
export const ANIMAL_MATCH_ENGINE_CONSTANTS_10 = ANIMAL_MATCH_CONSTANTS;
export const BUNNY_HUNTER_ENGINE_CONSTANTS_10 = BUNNY_HUNTER_CONSTANTS;
export const TETRIS_BATTLE_ENGINE_CONSTANTS_10 = TETRIS_BATTLE_CONSTANTS;
export const SNAKE_DUO_ENGINE_CONSTANTS_10 = SNAKE_DUO_CONSTANTS;
export const PINBALL_DUO_ENGINE_CONSTANTS_10 = PINBALL_DUO_CONSTANTS;
export const SPACE_SHOOTER_ENGINE_CONSTANTS_10 = SPACE_SHOOTER_CONSTANTS;
export const TANK_BATTLE_ENGINE_CONSTANTS_10 = TANK_BATTLE_CONSTANTS;
export const ZOMBIE_SHOOTER_ENGINE_CONSTANTS_10 = ZOMBIE_SHOOTER_CONSTANTS;

// GAMES_LIST
export const GAMES_LIST = [
  { id: '2048', name: '2048', category: 'puzzle', icon: '🔢', difficulty: 'medium' },
  { id: 'tetris', name: '俄罗斯方块', category: 'puzzle', icon: '🧱', difficulty: 'medium' },
  { id: 'snake', name: '贪吃蛇', category: 'puzzle', icon: '🐍', difficulty: 'easy' },
  { id: 'bounce', name: '弹球', category: 'puzzle', icon: '🏀', difficulty: 'easy' },
  { id: 'fusion2048', name: '融合2048', category: 'puzzle', icon: '✨', difficulty: 'hard' },
  { id: 'minesweeper', name: '扫雷', category: 'puzzle', icon: '💣', difficulty: 'medium' },
  { id: 'bejeweled', name: '宝石迷阵', category: 'puzzle', icon: '💎', difficulty: 'medium' },
  { id: 'sudoku', name: '数独', category: 'puzzle', icon: '🔢', difficulty: 'hard' },
  { id: 'subway', name: '地铁跑酷', category: 'arcade', icon: '🚇', difficulty: 'easy' },
  { id: 'fireice', name: '冰火人', category: 'arcade', icon: '❄️', difficulty: 'medium' },
  { id: 'goldminer', name: '黄金矿工', category: 'arcade', icon: '⛏️', difficulty: 'easy' },
  { id: 'pvz', name: '植物大战僵尸', category: 'arcade', icon: '🌻', difficulty: 'hard' },
  { id: 'sketchout', name: 'Sketchout', category: 'arcade', icon: '✏️', difficulty: 'medium' },
  { id: 'flappybird', name: 'Flappy Bird', category: 'arcade', icon: '🐦', difficulty: 'hard' },
  { id: 'pacman', name: 'Pacman', category: 'arcade', icon: '👻', difficulty: 'medium' },
  { id: 'stickmanhook', name: 'Stickman Hook', category: 'arcade', icon: '🪝', difficulty: 'hard' },
  { id: 'hexgl', name: 'HexGL', category: 'arcade', icon: '🏎️', difficulty: 'hard' },
  { id: 'templerun', name: 'Temple Run', category: 'arcade', icon: '🏃', difficulty: 'medium' },
  { id: 'onevone', name: '1v1', category: 'arcade', icon: '⚔️', difficulty: 'hard' },
  { id: 'crosscode', name: 'CrossCode', category: 'arcade', icon: '🌐', difficulty: 'hard' },
  { id: 'zuma', name: '祖玛', category: 'puzzle', icon: '🐸', difficulty: 'hard' },
  { id: 'linklink', name: '连连看', category: 'puzzle', icon: '🔗', difficulty: 'easy' },
  { id: 'sokoban', name: '推箱子', category: 'puzzle', icon: '📦', difficulty: 'medium' },
  { id: 'finddiff', name: '找茬', category: 'puzzle', icon: '🔍', difficulty: 'easy' },
  { id: 'onestroke', name: '一笔画', category: 'puzzle', icon: '✏️', difficulty: 'medium' },
  { id: 'pinball', name: '弹珠台', category: 'arcade', icon: '🎱', difficulty: 'medium' },
  { id: 'bowling', name: '保龄球', category: 'arcade', icon: '🎳', difficulty: 'easy' },
  { id: 'billiards', name: '台球', category: 'arcade', icon: '🎱', difficulty: 'medium' },
  { id: 'ringtoss', name: '套圈', category: 'arcade', icon: '🎯', difficulty: 'easy' },
  { id: 'enhancedbreakout', name: 'Breakout', category: 'arcade', icon: '🧱', difficulty: 'medium' },
  { id: 'skiing', name: '滑雪大冒险', category: 'arcade', icon: '⛷️', difficulty: 'medium' },
  { id: 'dancingline', name: '跳舞的线', category: 'arcade', icon: '💃', difficulty: 'hard' },
  { id: 'subway2', name: '地铁跑酷2', category: 'arcade', icon: '🚇', difficulty: 'easy' },
  { id: 'cliffrunner', name: '悬崖奔跑', category: 'arcade', icon: '🏔️', difficulty: 'hard' },
  { id: 'speedescape', name: '极速逃脱', category: 'arcade', icon: '💨', difficulty: 'medium' },
  { id: 'cooprun', name: '双人跑酷', category: 'co-op', icon: '🏃', difficulty: 'medium' },
  { id: 'tetrisbattle', name: '俄罗斯方块对战', category: 'co-op', icon: '🧱', difficulty: 'hard' },
  { id: 'snakeduo', name: '双人贪吃蛇', category: 'co-op', icon: '🐍', difficulty: 'medium' },
  { id: 'bunnyhunter', name: '猎人射兔子', category: 'co-op', icon: '🐰', difficulty: 'easy' },
  { id: 'pinballduo', name: '双人弹珠', category: 'co-op', icon: '🎱', difficulty: 'medium' },
  { id: 'thunder', name: '雷电', category: 'shooting', icon: '⚡', difficulty: 'medium' },
  { id: 'spaceshooter', name: '太空射击', category: 'shooting', icon: '🚀', difficulty: 'medium' },
  { id: 'tankbattle', name: '坦克大战', category: 'shooting', icon: '🎖️', difficulty: 'hard' },
  { id: 'bubbleshooter', name: '泡泡射击', category: 'shooting', icon: '🫧', difficulty: 'medium' },
  { id: 'zombieshooter', name: '僵尸射击', category: 'shooting', icon: '🧟', difficulty: 'hard' },
  { id: 'monopoly', name: '大富翁', category: 'strategy', icon: '💰', difficulty: 'medium' },
  { id: 'happyfarm', name: '开心农场', category: 'strategy', icon: '🌾', difficulty: 'easy' },
  { id: 'cookingmaster', name: '烹饪大师', category: 'strategy', icon: '🍳', difficulty: 'medium' },
  { id: 'shopmaster', name: '商店大师', category: 'strategy', icon: '🏪', difficulty: 'medium' },
  { id: 'fruitninja', name: '水果忍者', category: 'reaction', icon: '🍎', difficulty: 'hard' },
  { id: 'whackamole', name: '打地鼠', category: 'reaction', icon: '🐹', difficulty: 'easy' },
  { id: 'colormatch', name: '颜色匹配', category: 'reaction', icon: '🎨', difficulty: 'medium' },
  { id: 'braintest', name: '脑力测试', category: 'reaction', icon: '🧠', difficulty: 'medium' },
  { id: 'chess', name: '中国象棋', category: 'board', icon: '♟️', difficulty: 'hard' },
  { id: 'gobang', name: '五子棋', category: 'board', icon: '⭕', difficulty: 'medium' },
  { id: 'ludo', name: '飞行棋', category: 'board', icon: '🎲', difficulty: 'easy' },
  { id: 'towerdefense', name: '经典塔防', category: 'tower', icon: '🏰', difficulty: 'medium' },
  { id: 'catapultdefense', name: '弹射塔防', category: 'tower', icon: '💥', difficulty: 'medium' },
  { id: 'magictower', name: '魔法塔防', category: 'tower', icon: '🔮', difficulty: 'hard' },
  { id: 'desertwar', name: '沙漠战争', category: 'tower', icon: '🏜️', difficulty: 'hard' },
  { id: 'iceagedefense', name: '冰时代塔防', category: 'tower', icon: '❄️', difficulty: 'medium' },
  { id: 'rhythmmaster', name: '节奏大师', category: 'rhythm', icon: '🎵', difficulty: 'hard' },
  { id: 'djmixer', name: 'DJ混音', category: 'rhythm', icon: '🎧', difficulty: 'medium' },
  { id: 'pianotiles', name: '钢琴块', category: 'rhythm', icon: '🎹', difficulty: 'hard' },
  { id: 'beatracer', name: '节拍赛车', category: 'rhythm', icon: '🏎️', difficulty: 'medium' },
  { id: 'musichero', name: '音乐英雄', category: 'rhythm', icon: '🎸', difficulty: 'hard' },
  { id: 'candycrush', name: '糖果传奇', category: 'match3', icon: '🍬', difficulty: 'medium' },
  { id: 'gemblast', name: '宝石爆破', category: 'match3', icon: '💎', difficulty: 'medium' },
  { id: 'bubblepop', name: '泡泡爆破', category: 'match3', icon: '🫧', difficulty: 'easy' },
  { id: 'cookiismatch', name: '饼干消消乐', category: 'match3', icon: '🍪', difficulty: 'easy' },
  { id: 'animalmatch', name: '动物消消乐', category: 'match3', icon: '🐱', difficulty: 'easy' },
  { id: 'pixelfighter', name: '像素格斗', category: 'fighting', icon: '👊', difficulty: 'hard' },
  { id: 'brawlstars', name: '乱斗明星', category: 'fighting', icon: '⭐', difficulty: 'medium' },
  { id: 'karatechamp', name: '空手道冠军', category: 'fighting', icon: '🥋', difficulty: 'hard' },
  { id: 'samuraislash', name: '武士斩击', category: 'fighting', icon: '⚔️', difficulty: 'hard' },
  { id: 'wrestlemania', name: '摔跤狂热', category: 'fighting', icon: '🤼', difficulty: 'medium' },
  { id: 'huarongdao', name: '华容道', category: 'puzzle2', icon: '🧩', difficulty: 'hard' },
  { id: 'numberslide', name: '数字华容道', category: 'puzzle2', icon: '🔢', difficulty: 'medium' },
  { id: 'pipeconnect', name: '水管连接', category: 'puzzle2', icon: '🔧', difficulty: 'medium' },
  { id: 'memorymatch', name: '记忆翻牌', category: 'puzzle2', icon: '🃏', difficulty: 'easy' },
  { id: 'wordsearch', name: '文字搜索', category: 'puzzle2', icon: '📝', difficulty: 'medium' },
  { id: 'virtualpet', name: '虚拟宠物', category: '养成', icon: '🐾', difficulty: 'easy' },
  { id: 'fishtank', name: '养鱼大亨', category: '养成', icon: '🐠', difficulty: 'easy' },
  { id: 'gardengarden', name: '花园种花', category: '养成', icon: '🌸', difficulty: 'easy' },
  { id: 'cookiebakery', name: '饼干面包店', category: '养成', icon: '🥐', difficulty: 'medium' },
  { id: 'pokemon', name: '口袋妖怪', category: '养成', icon: '🎮', difficulty: 'medium' },
  { id: 'angrybirds', name: '愤怒的小鸟', category: 'physics', icon: '🐦', difficulty: 'medium' },
  { id: 'doodlejump', name: '涂鸦跳跃', category: 'physics', icon: '✏️', difficulty: 'hard' },
  { id: 'bowlingmaster', name: '保龄球大师', category: 'physics', icon: '🎳', difficulty: 'medium' },
  { id: 'pinballphysics', name: '弹球物理', category: 'physics', icon: '🎱', difficulty: 'medium' },
  { id: 'cutrope', name: '切割绳子', category: 'physics', icon: '✂️', difficulty: 'medium' },
];

// Game constants for compatibility
export const GAME_CONSTANTS: Record<string, any> = {
  DEFAULT_CANVAS_WIDTH: 600,
  DEFAULT_CANVAS_HEIGHT: 500,
  DEFAULT_GRID_SIZE: 8,
  DEFAULT_CELL_SIZE: 50,
  DEFAULT_GAME_DURATION: 60,
  DEFAULT_ROUND_DURATION: 90,
};
