export const GEOMETRY_WARS_CONSTANTS = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,
  PLAYER_SIZE: 15,
  BULLET_SIZE: 4,
  ENEMY_SIZE: 20,
  PLAYER_SPEED: 5,
  PLAYER_BULLET_SPEED: 10,
  ENEMY_SPEED: 2,
};

export const GEOMETRY_WARS_ENGINE_CONSTANTS = GEOMETRY_WARS_CONSTANTS;
export const GEOMETRY_WARS_CONSTANTS_2 = GEOMETRY_WARS_CONSTANTS;
export const GEOMETRY_WARS_CONSTANTS_3 = GEOMETRY_WARS_CONSTANTS;
export const GEOMETRY_WARS_CONSTANTS_4 = GEOMETRY_WARS_CONSTANTS;
