export const RAIDEN_ENHANCED_CONSTANTS = {
  CANVAS_WIDTH: 600,
  CANVAS_HEIGHT: 800,
  PLAYER_WIDTH: 40,
  PLAYER_HEIGHT: 50,
  BULLET_WIDTH: 6,
  BULLET_HEIGHT: 15,
  ENEMY_WIDTH: 35,
  ENEMY_HEIGHT: 40,
  PLAYER_SPEED: 6,
  PLAYER_BULLET_SPEED: 12,
  ENEMY_BULLET_SPEED: 5,
  BOSS_WIDTH: 150,
  BOSS_HEIGHT: 100,
};

export const RAIDEN_ENHANCED_ENGINE_CONSTANTS = RAIDEN_ENHANCED_CONSTANTS;
export const RAIDEN_ENHANCED_CONSTANTS_2 = RAIDEN_ENHANCED_CONSTANTS;
export const RAIDEN_ENHANCED_CONSTANTS_3 = RAIDEN_ENHANCED_CONSTANTS;
export const RAIDEN_ENHANCED_CONSTANTS_4 = RAIDEN_ENHANCED_CONSTANTS;
