export const SPACE_BULLET_CONSTANTS = {
  CANVAS_WIDTH: 600,
  CANVAS_HEIGHT: 800,
  PLAYER_SIZE: 35,
  BULLET_SIZE: 6,
  ENEMY_SIZE: 30,
  POWERUP_SIZE: 25,
  PLAYER_SPEED: 5,
  PLAYER_BULLET_SPEED: 12,
  ENEMY_BULLET_SPEED: 4,
};

export const SPACE_BULLET_ENGINE_CONSTANTS = SPACE_BULLET_CONSTANTS;
export const SPACE_BULLET_CONSTANTS_2 = SPACE_BULLET_CONSTANTS;
export const SPACE_BULLET_CONSTANTS_3 = SPACE_BULLET_CONSTANTS;
export const SPACE_BULLET_CONSTANTS_4 = SPACE_BULLET_CONSTANTS;
